parameters:
  - name: target
    type: string
  - name: tag
    type: string
  - name: working_directory
    type: string
  - name: profiles_directory
    type: string
  - name: snowflake_target_database
    type: string
  - name: snowflake_authenticator_value
    type: string   
  - name: env_name
    type: string
    default: dbt-env    

steps:
      
  - powershell: |
        if(Test-Path -Path "partial_parse.msgpack") {
          Remove-Item -Path "partial_parse.msgpack" -Force
        }
        if(Test-Path -Path "graph.gpickle") {
          Remove-Item -Path "graph.gpickle" -Force
        }
    displayName: Clean Target
    workingDirectory: ${{ parameters.working_directory }}/target

  - bash: |
      source $DBT_ENV_NAME/bin/activate  
      dbt run --profiles-dir=${{ parameters.profiles_directory }} --target=${{ parameters.target }} -models tag:${{ parameters.tag }}
    displayName: Run DBT without Unit-tests
    workingDirectory: ${{ parameters.working_directory }}
    env:
      DBT_ENV_NAME: ${{ parameters.env_name }}
      snowflake-target-database: ${{ parameters.snowflake_target_database }}
      snowflake-username: $(snowflake-username)
      snowflake-account: $(snowflake-account)
      snowflake-password: ${{ parameters.snowflake_authenticator_value }}
      snowflake-warehouse: $(snowflake-warehouse)
      snowflake-role: $(snowflake-role)
      snowflake-private-key-passphrase: $(snowflake-private-key-passphrase)