parameters:
  - name: working_directory
    type: string
  - name: subscription_authorisation
    type: string
  - name: storage_account
    type: string
  - name: target_container
    type: string
  - name: source_directory
    type: string
  - name: snowflake_target_database
    type: string

steps:
  - task: AzureCLI@2
    displayName: 'Upload manifest to blob storage'
    inputs:
      azureSubscription: '${{ parameters.subscription_authorisation }}'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az storage blob upload \
        --container-name '${{ parameters.target_container }}' \
        --name '${{ parameters.snowflake_target_database }}_manifest.json' \
        --account-name '${{ parameters.storage_account }}' \
        --file '${{ parameters.working_directory }}/${{ parameters.source_directory }}/manifest.json' \
        --content-type 'application/json' \
        --overwrite
