parameters:
  - name: working_directory
    type: string
  - name: target_directory
    type: string
  - name: env_name
    type: string
    default: aws-env
  - name: storage_account
    default: dave-dataops
  - name: snowflake_target_database

steps:
  - bash: |
      source $AWS_ENV_NAME/bin/activate
      aws s3 cp ${{ parameters.target_directory }}/manifest.json s3://${{ parameters.storage_account }}/${{ parameters.snowflake_target_database }}_manifest.json
    displayName: Upload dbt manifest for database
    workingDirectory: ${{ parameters.working_directory }}
    env:
      AWS_ENV_NAME: ${{ parameters.env_name }}