name: Clone the Manifest for the cloned database
description: Clones an existing dbt manifest.json for the database
inputs:
  use-azure-federated-login:
    description: Specifies if the action should use Azure Federated Login or Azure Service Principal ClientID/ClientSecret
    default: false
  resource-group:
    description: The resource group where the storage account is located
    required: true
  storage-account:
    description: The name of the storage account
    required: true
  snowflake-source-database:
    description: The name of the database to get the manifest for
    required: true
  snowflake-target-database:
    description: The name of the database to set the manifest for
    required: true
  azure-credentials:
    description: The Azure credentials to use for authentication
    required: false
  azure-client-id:
    description: The Azure client ID to use for authentication
    required: false
  azure-tenant-id:
    description: The Azure tenant ID to use for authentication
    required: false
  azure-subscription-id:
    description: The Azure subscription ID to use for authentication
    required: false

permissions:
  id-token: write
  contents: read
runs:
  using: "composite"
  steps:
      - name: Authenticate to Azure as a Service Principal
        uses: azure/login@v2
        condition: ${{ inputs.use-azure-federated-login == 'false' }}
        with:
          creds: ${{ inputs.azure-credentials }}

      - name: Authenticate to Azure as a Service Principal (ODIC)
        uses: azure/login@v2
        condition: ${{ inputs.use-azure-federated-login == 'true' }}
        with:
          client-id: ${{ inputs.azure-client-id }}
          tenant-id: ${{ inputs.azure-tenant-id }}
          subscription-id: ${{ inputs.azure-subscription-id }}
          enable-AzPSSession: true


      - name: Clone Manifest file
        uses: azure/CLI@v2
        with:
          inlineScript: |
              if $(az storage blob exists --container-name 'manifests' --name ${{ inputs.snowflake-source-database }}_manifest.json --account-name ${{ inputs.storage-account }} --query exists --auth-mode login)
              then
                echo " ==> DBT manifest exists in the container, copying file"
                az storage blob copy start \
                  --account-name ${{ inputs.storage-account }} \
                  --destination-container 'manifests' \
                  --destination-blob '${{ inputs.snowflake-target-database }}_manifest.json' \
                  --source-account-name ${{ inputs.storage-account }} \
                  --source-container 'manifests' \
                  --source-blob '${{ inputs.snowflake-source-database }}_manifest.json' \
                  --auth-mode login  
              fi

      # Azure logout
      - name: logout
        shell: bash
        run: |
              az logout
        if: always()