name: Clone Database to Unit Test
description: Generates a test database
inputs:
  working-directory:
    description: The directory where the scripts are located
    required: true
  source-database:
    description: The source database to clone
    required: true
  target-database:
    description: The target database name to clone to
    required: true
  snowflake-account:
    description: The Snowflake account name
    required: true
  snowflake-username:
    description: The Snowflake username
    required: true
  snowflake-authenticator:
    description: The Snowflake authenticator
    required: true
    default: "password"
  snowflake-privatekey-passphrase:
    description: The passphrase for the private key
    required: false
  snowflake-authenticator-value:
    description: The value for the authenticator (Password or Private Key Path)
    required: true
  snowflake-role:
    description: The Snowflake role
    required: true
  snowflake-warehouse:
    description: The Snowflake warehouse
    required: true
  database-comment:
    description: The Comment to add to the clone database
    required: false

runs:
  using: "composite"
  steps:
    - name: Find and replace the placeholders
      run: |
        sed -i 's/<<TARGET_DATABASE_NAME>>/${{ inputs.target-database }}/g' database-clone.sql
        sed -i 's/<<SOURCE_DATABASE_NAME>>/${{ inputs.source-database }}/g' database-clone.sql
        sed -i 's/<<CLONE_DATABASE_COMMENT>>/${{ inputs.database-comment }}/g' database-clone.sql
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
    - name: Download SnowSQL
      shell: bash
      run:  curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
    - name: Install SnowSQL
      shell: bash
      run: SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

    - name: Execute SQL against Snowflake (Password Based Authentication)
      if: and(succeeded(), eq(${{ inputs.snowflake-authenticator }}, 'password'))
      run: |
         ~/snowflake/snowsql \
            -a $SNOWSQL_ACCOUNT \
            -u $SNOWSQL_USER \
            -d $SNOWSQL_DATABASE \
            -w $SNOWSQL_WAREHOUSE \
            -r $SNOWSQL_ROLE \
            -f database-clone.sql
      env:
        SNOWSQL_ACCOUNT: ${{ inputs.snowflake-account }}
        SNOWSQL_USER: ${{ inputs.snowflake-username }}
        SNOWSQL_PWD: ${{ inputs.snowflake-authenticator-value }}
        SNOWSQL_DATABASE: ${{ inputs.source-database }}
        SNOWSQL_ROLE: ${{ inputs.snowflake-role }}
        SNOWSQL_WAREHOUSE: ${{ inputs.snowflake-warehouse }}
      working-directory: ${{ inputs.working-directory }}

    - name: Execute SQL against Snowflake (Key Based Authentication)
      if: and(succeeded(), eq(${{ inputs.snowflake-authenticator }}, 'private_key_path'))
      run: |
         ~/snowflake/snowsql \
            -a $SNOWSQL_ACCOUNT \
            -u $SNOWSQL_USER \
            -d $SNOWSQL_DATABASE \
            -w $SNOWSQL_WAREHOUSE \
            -r $SNOWSQL_ROLE \
            -f database-clone.sql \
            --private-key-path $PRIVATE_KEY_PATH
      env:
        SNOWSQL_ACCOUNT: ${{ inputs.snowflake-account }}
        SNOWSQL_USER: ${{ inputs.snowflake-username }}
        SNOWSQL_DATABASE: ${{ inputs.source-database }}
        SNOWSQL_ROLE: ${{ inputs.snowflake-role }}
        SNOWSQL_WAREHOUSE: ${{ inputs.snowflake-warehouse }}
        PRIVATE_KEY_PATH: ${{ inputs.snowflake-authenticator-value }}
        SNOWSQL_PRIVATE_KEY_PASSPHRASE: $(inputs.snowflake-privatekey-passphrase)
      working-directory: ${{ inputs.working-directory }}

