name: Clone Database to Unit Test
description: Generates a test database
inputs:
  working-directory:
    description: The directory where the scripts are located
    required: true
  source-database:
    description: The source database to clone
    required: true
  target-database:
    description: The target database name to clone to
    required: true
  snowflake-account:
    description: The Snowflake account name
    required: true
  snowflake-username:
    description: The Snowflake username
    required: true
  snowflake-password:
    description: The Snowflake password
    required: true
  snowflake-role:
    description: The Snowflake role
    required: true
  snowflake-warehouse:
    description: The Snowflake warehouse
    required: true
  data-lake-url:
    description: The Data Lake URL
    required: false
  storage-integration-name:
    description: The Storage Integration Name
    required: false
  storage-account-name:
    description: The Storage Account Name for Storeage Integration URL 
    required: false
  database-comment:
    description: The Comment to add to the clone database
    required: false

runs:
  using: "composite"
  steps:
    - name: Find and replace the placeholders
      run: |
        sed -i 's/<<TARGET_DATABASE_NAME>>/${{ inputs.target-database }}/g' database-clone.sql
        sed -i 's/<<SOURCE_DATABASE_NAME>>/${{ inputs.source-database }}/g' database-clone.sql
        sed -i 's/<<CLONE_DATABASE_COMMENT>>/${{ inputs.database-comment }}/g' database-clone.sql
        sed -i 's/<<STORAGE_INTEGRATION_NAME>>/${{ inputs.storage-integration-name }}/g' database-clone.sql
        sed -i 's/<<STORAGE_ACCOUNT_NAME>>/${{ inputs.storage-account-name }}/g' database-clone.sql
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
    - name: Download SnowSQL
      shell: bash
      run:  curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
    - name: Install SnowSQL
      shell: bash
      run: SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
    - name: Execute SQL against Snowflake
      shell: bash    
      run: |
         ~/snowflake/snowsql \
            -a $SNOWSQL_ACCOUNT \
            -u $SNOWSQL_USER \
            -d $SNOWSQL_DATABASE \
            -w $SNOWSQL_WAREHOUSE \
            -f database-clone.sql
      env:
        SNOWSQL_ACCOUNT: ${{ inputs.snowflake-account }}
        SNOWSQL_USER: ${{ inputs.snowflake-username }}
        SNOWSQL_PWD: ${{ inputs.snowflake-password }}
        SNOWSQL_DATABASE: ${{ inputs.source-database }}
        SNOWSQL_WAREHOUSE: ${{ inputs.snowflake-warehouse }}
      working-directory: ${{ inputs.working-directory }}

