name: Run DBT
description: Runs DBT
inputs:
  target:
    required: true
    description: The target to run DBT against
  working-directory:
    required: true
    description: The directory where the DBT project is located
  profiles-directory:
    required: true
    description: The directory where the DBT profiles are located
  snowflake-account:
    required: true
    description: The snowflake account to use
  snowflake-username:
    required: true
    description: The snowflake username to use
  snowflake-password:
    required: true
    description: The snowflake password to use
  snowflake-role:
    required: true
    description: The snowflake role to use
  snowflake-warehouse:
    required: true
    description: The snowflake warehouse to use
  snowflake-target-database:
    required: true
    description: The snowflake target database to use
  archive-outputs:
    description: Whether to archive test results
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Run DBT Schema Only Tests
      if: inputs.target  != 'unit-test'
      shell: bash
      run: |
        dbt test --profiles-dir=${{ inputs.profiles-directory }} --target=${{ inputs.target }} --exclude tag:unit_test
      working-directory: ${{ inputs.working-directory }}
      env:
        snowflake-account: ${{ inputs.snowflake-account }}
        snowflake-username: ${{ inputs.snowflake-username }}
        snowflake-role: ${{ inputs.snowflake-role }}
        snowflake-warehouse: ${{ inputs.snowflake-warehouse }}
        snowflake-target-database: ${{ inputs.snowflake-target-database }}
        snowflake-password: ${{ inputs.snowflake-password }}

    - name: Run DBT Schema Tests and unit-tests
      if: inputs.target  == 'unit-test'
      shell: bash
      run: |
        dbt test --profiles-dir=${{ inputs.profiles-directory }} --target=${{ inputs.target }}
      working-directory: ${{ inputs.working-directory }}
      env:
        snowflake-account: ${{ inputs.snowflake-account }}
        snowflake-username: ${{ inputs.snowflake-username }}
        snowflake-role: ${{ inputs.snowflake-role }}
        snowflake-warehouse: ${{ inputs.snowflake-warehouse }}
        snowflake-target-database: ${{ inputs.snowflake-target-database }}
        snowflake-password: ${{ inputs.snowflake-password }}

    - name: Archive Dbt Test Results
      uses: actions/upload-artifact@v3
      if: ${{ inputs.archive-outputs == 'true' }}
      with:
          name: dbt-test-results
          path: 
            ${{ inputs.working-directory }}/target/run_results.json