name: Determine the deployment target name
description: Target name of the profile to use
outputs:
  target-name:
    description: The name of the current branch to target
    value: ${{ steps.determine-branch-name.outputs.target-name }}
runs:
  using: "composite"
  steps:
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: TARGET_NAME
        id: determine-branch-name
        shell: bash
        run: |
          echo "target-name=$(echo ${{ env.BRANCH_NAME }})" >> $GITHUB_OUTPUT

      - name: show target name
        shell: bash
        run: |
          echo "Target: ${{ steps.determine-branch-name.outputs.target-name }}"