name: Run DBT
description: Runs DBT
inputs:
  target:
    description: The target to run DBT against
    required: true
  working-directory:
    description: The directory where the DBT project is located
    required: true
  profiles-directory:
    description: The directory where the DBT profiles are located
    required: true
  snowflake-account:
    description: The snowflake account to use
    required: true
  snowflake-username:
    description: The snowflake username to use
    required: true
  snowflake-privatekey-passphrase:
    description: The passphrase for the private key
    required: false
  snowflake-authenticator-value:
    description: The value for the authenticator (Password or Private Key Path)
    required: true
  snowflake-role:
    description: The snowflake role to use
    required: true
  snowflake-warehouse:
    description: The snowflake warehouse to use
    required: true
  snowflake-target-database:
    description: The snowflake target database to use
    required: true

runs:
  using: "composite"
  steps:
    - name: Clean target
      shell: pwsh
      run: |
         if(Test-Path -Path ".\target\partial_parse.msgpack") {
            Remove-Item -Path ".\target\partial_parse.msgpack" -Force
         }
         if(Test-Path -Path ".\target\graph.gpickle") {
          Remove-Item -Path ".\target\graph.gpickle" -Force
         }
      working-directory: ${{ inputs.working-directory }}

    - name: Run DBT without Unit-tets
      if: inputs.target  != 'unit-test'
      shell: pwsh
      run: |
        dbt compile --profiles-dir=${{ inputs.profiles-directory }} --target=${{ inputs.target }} --exclude tag:unit_test
        dbt seed --profiles-dir=${{ inputs.profiles-directory }} --target=${{ inputs.target }} --exclude path:seeds/unit_tests
        if(Test-Path -Path ".\manifest.json" -PathType Leaf) {
          echo " ==> Previous Manifest file found, running dbt run for release"
          dbt run -s state:modified --defer --state . --profiles-dir=${{ inputs.profiles-directory }} --target=${{ inputs.target }} --exclude tag:unit_test 
        } else {
            echo " ==> No Previous Manifest file found, running dbt run fo release"
            dbt run --profiles-dir=${{ inputs.profiles-directory }} --target=${{ inputs.target }} --exclude tag:unit_test
        }
      working-directory: ${{ inputs.working-directory }}
      env:
        snowflake-account: ${{ inputs.snowflake-account }}
        snowflake-username: ${{ inputs.snowflake-username }}
        snowflake-role: ${{ inputs.snowflake-role }}
        snowflake-warehouse: ${{ inputs.snowflake-warehouse }}
        snowflake-target-database: ${{ inputs.snowflake-target-database }}
        snowflake-password: ${{ inputs.snowflake-authenticator-value }}
        snowflake-private-key-password: $(inputs.snowflake-privatekey-passphrase)

    - name: Run DBT with unit-tests
      if: inputs.target  == 'unit-test'
      shell: pwsh
      run: |
        dbt compile --profiles-dir=${{ inputs.profiles-directory }} --target=${{ inputs.target }} --exclude tag:unit_test
        dbt seed --profiles-dir=${{ inputs.profiles-directory }} --target=${{ inputs.target }} --full-refresh
        if(Test-Path -Path ".\manifest.json" -PathType Leaf) {
          echo " ==> Previous Manifest file found, running dbt run for unit tests"
          dbt run -s state:modified --defer --state . --profiles-dir=${{ inputs.profiles-directory }} --target=${{ inputs.target }}
        } else {
          echo " ==> No Previous Manifest file found, running dbt run for unit tests"
          dbt run --profiles-dir=${{ inputs.profiles-directory }} --target=${{ inputs.target }}
        }

      working-directory: ${{ inputs.working-directory }}
      env:
        snowflake-account: ${{ inputs.snowflake-account }}
        snowflake-username: ${{ inputs.snowflake-username }}
        snowflake-role: ${{ inputs.snowflake-role }}
        snowflake-warehouse: ${{ inputs.snowflake-warehouse }}
        snowflake-target-database: ${{ inputs.snowflake-target-database }}
        snowflake-password: ${{ inputs.snowflake-authenticator-value }}
        snowflake-private-key-password: $(inputs.snowflake-privatekey-passphrase)