name: Dbt Setup
description: Setups Dbt Components
inputs:
  working-directory:
    description: The directory where the DBT project is located
    required: true
    default: './dbt'

runs:
  using: "composite"
  steps:
    - name: install Python
      uses: "actions/setup-python@v2"
      with:
        python-version: 3.10

    - name: install components
      shell: bash
      run: pip install -r .deployrequirements
      working-directory: ${{ inputs.working-directory }}

    - name: setup dbt dependencies
      shell: bash
      run: |
        dbt deps
      working-directory: ${{ inputs.working-directory }}