name: Publish Dbt Docs to Docs Repository
description: Publish the dbt docs to Docs Repository
inputs:
  target-directory:
    description: The directory where the DBT output is located
    required: true
  working-directory:
    description: The directory where the project is located
    required: true
  dbt-directory:
    description: The directory where dbt is located
    required: true
  branch_based_folder:
    description: The sub folder to add the files to in the storage account
    required: false
    default: 'yes'
  docs_repo:
    description: The name of the repository where the docs are located
    required: false
  docs_repo_folder:
    description: The folder where the files are located
    required: false
  docs_repo_pat:
    description: The PAT to access the repository
    required: false

runs:
  using: "composite"
  steps:
      - name: Get branch name
        if: github.event_name != 'pull_request'
        id: get-branch-name
        shell: bash
        run: |
          branch_name=$(git branch --show-current)
          echo "Current branch: $branch_name"
          echo "branch-name=$(echo $branch_name)" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.working-directory }}

      - name: List Branches
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          git fetch --all
          git branch -r > branches.txt
          ls
        working-directory: ${{ inputs.working-directory }}

      - name: Find and replace the placeholders
        if: github.event_name != 'pull_request'
        shell: pwsh
        run: |
          $branch_file = "../../branches.txt"
          Write-Host "Branch File: $branch_file"
          Write-Host "Branch Name: ${{ steps.get-branch-name.outputs.branch-name }}"
          (Get-Content -Path "manifest.json") -replace "<<BRANCH_NAME>>", "${{ steps.get-branch-name.outputs.branch-name }}" | Set-Content -Path "manifest.json"
          (Get-Content -Path "index.html") -replace "manifest.json", "/${{ steps.get-branch-name.outputs.branch-name }}/manifest.json" | Set-Content -Path "index.html"
          (Get-Content -Path "index.html") -replace "catalog.json", "/${{ steps.get-branch-name.outputs.branch-name }}/catalog.json" | Set-Content -Path "index.html"
        working-directory: ${{ inputs.working-directory }}/${{ inputs.dbt-directory }}/${{ inputs.target-directory }}


      - name: Clone Target Repository
        uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.docs_repo }}
          token: ${{ inputs.docs_repo_pat }}
          path: docsrepo


      - name: Push Item
        if: github.event_name != 'pull_request'
        shell: bash
        working-directory: "${{ inputs.working-directory }}/.."
        run: |
          echo "===> Changing Directory to docsrepo"
          cd docsrepo

          # Push to the target repository here
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          # Configure paths relative to root
          manifest_file_path="../../../${{ inputs.working-directory }}/${{ inputs.dbt-directory }}/${{ inputs.target-directory }}/manifest.json"
          catalog_file_path="../../../${{ inputs.working-directory }}/${{ inputs.dbt-directory }}/${{ inputs.target-directory }}/catalog.json"
          index_file_path="../../../${{ inputs.working-directory }}/${{ inputs.dbt-directory }}/${{ inputs.target-directory }}/index.html"
          branches_file_path="../../../${{ inputs.working-directory }}/branches.txt"
          cd ${{ inputs.docs_repo_folder }}

          cd wwwroot

          branch_name=$(grep -r "$${{ steps.get-branch-name.outputs.branch-name }}$" "$branches_file_path")
          IFS='/' read -ra folders <<< "${branch_name:9}"

          for folder in "${folders[@]}"; do
            if test -d $folder; then
                echo "Directory $folder exists."
            else
                echo "Directory $folder does not exists ... creating it"
                mkdir $folder
            fi
            echo "current: $folder"
            echo "target: $target_folder"
                manifest_file_path="../$manifest_file_path"
                catalog_file_path="../$catalog_file_path"
                index_file_path="../$index_file_path"
            cd $folder
          done

          cp -f $manifest_file_path .
          cp -f $catalog_file_path .
          cp -f $index_file_path .
          git add -A
          git commit -m "Added dbt docs for ${{ steps.get-branch-name.outputs.branch-name }}"
          for folder in "${folders[@]}"; do
            cd ..
          done
          for folder in $(find . -type d); do
            echo "checking folder ${folder:2:} in file $branches_file_path"
            if grep -q "${folder:2:}" $branches_file_path; then
              echo "Keeping $folder"
            elif [[ "$folder" == "./css"* ]]; then
              echo "Keeping $folder"
            elif [[ "$folder" == "./images"* ]]; then
              echo "Keeping $folder"
            elif [[ "$folder" == "./js"* ]]; then
              echo "Keeping $folder"
            elif [[ "$folder" == "./lib"* ]]; then
              echo "Keeping $folder"
            elif [ "$folder" == "./${{ steps.get-branch-name.outputs.branch-name }}/" ]; then
              echo "Keeping current branch $folder"
            else
              echo "Deleting $folder"
              rm -rf $folder
              git rm -r $folder
              git commit -m "Delete Old branch $folder"
            fi
          done
          git push
