name: Publish Dbt Docs to Docs Repository
description: Publish the dbt docs to Docs Repository
inputs:
  target-directory:
    description: The directory where the DBT output is located
    required: true
  working-directory:
    description: The directory where dbt is located
    required: true
  branch_based_folder:
    description: The sub folder to add the files to in the storage account
    required: false
    default: 'yes'
  docs_repo:
    description: The name of the repository where the docs are located
    required: false
  docs_repo_folder:
    description: The folder where the files are located
    required: false
  docs_repo_pat:
    description: The PAT to access the repository
    required: false

runs:
  using: "composite"
  steps:
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Get Manifest and Catalog Paths
        shell: bash
        run: |
          echo "MANIFEST_FILE=$(echo /${{ env.BRANCH_NAME }}/manifest.json)" >> $GITHUB_ENV
          echo "CATALOG_FILE=$(echo /${{ env.BRANCH_NAME }}/catalog.json)" >> $GITHUB_ENV

      - name: Find and replace the placeholders
        shell: pwsh
        run: |
          sed -i 's|<<BRANCH_NAME>>|${{ env.BRANCH_NAME }}|g' manifest.json
          if("${{ inputs.branch_based_folder }}" -eq "yes") {
            sed -i 's|manifest.json|${{ env.MANIFEST_FILE }}|g' index.html
            sed -i 's|catalog.json|${{ env.CATALOG_FILE }}|g' index.html
          }
        working-directory: ${{ inputs.working-directory }}/${{ inputs.target-directory }}

      - name: List Branches
        shell: bash
        run: |
          git fetch --all
          git branch -r > branches.txt

      - name: Clone Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.docs_repo }}
          token: ${{ inputs.docs_repo_pat }}
          path: docsrepo

      - name: Push Item
        shell: bash
        run: |
          # Push to the target repository here
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          # Root Contents
          manifest_file_path="../../../../${{ inputs.working-directory }}/${{ inputs.target-directory }}/manifest.json"
          catalog_file_path="../../../../${{ inputs.working-directory }}/${{ inputs.target-directory }}/catalog.json"
          index_file_path="../../../../${{ inputs.working-directory }}/${{ inputs.target-directory }}/index.html"
          branches_file_path="../../../branches.txt"
          cd ./docsrepo/${{ inputs.docs_repo_folder }}
          cd ./wwwroot
          if test -d ${{ env.BRANCH_NAME }}; then
            echo "Directory ${{ env.BRANCH_NAME }} exists."
          else
            echo "Directory ${{ env.BRANCH_NAME }} does not exists."
            mkdir ${{ env.BRANCH_NAME }}
          fi
          cd ./${{ env.BRANCH_NAME }}
          cp -f $manifest_file_path .
          cp -f $catalog_file_path .
          cp -f $index_file_path .
          git add -A
          git commit -m "Added dbt docs for ${{ env.BRANCH_NAME }}"
          cd ..
          find . -type d | while read folder; do
            if grep -q "$folder" $branches_file_path; then
                echo "Deleting $folder"
                rm -rf "$folder"
                git rm -r directory
                git commit -m "Delete Old branch $folder"
            fi
          done

          git push
