name: Generate Docs
description: Generates dbt documents
inputs:
  target:
    description: The target to run DBT against
    required: true
  working-directory:
    description: The directory where the DBT project is located
    required: true
  profiles-directory:
    description: The directory where the DBT profiles are located
    required: true
  snowflake-account:
    description: The snowflake account to use
    required: true
  snowflake-username:
    description: The snowflake username to use
    required: true
  snowflake-password:
    description: The snowflake password to use
    required: true
  snowflake-role:
    description: The snowflake role to use
    required: true
  snowflake-warehouse:
    description: The snowflake warehouse to use
    required: true
  snowflake-target-database:
    description: The snowflake target database to use
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate DBT docs without Unit-tets
      shell: bash
      run: |
        dbt docs generate --profiles-dir=${{ inputs.profiles-directory }} --target=${{ inputs.target }} --exclude tag:unit_test
      working-directory: ${{ inputs.working-directory }}
      env:
        snowflake-account: ${{ inputs.snowflake-account }}
        snowflake-username: ${{ inputs.snowflake-username }}
        snowflake-role: ${{ inputs.snowflake-role }}
        snowflake-warehouse: ${{ inputs.snowflake-warehouse }}
        snowflake-target-database: ${{ inputs.snowflake-target-database }}
        snowflake-password: ${{ inputs.snowflake-password }}

    - name: Archive Dbt Docs
      uses: actions/upload-artifact@v3
      with:
          name: dbt-docs
          path: |
            ${{ inputs.working-directory }}/target/catalog.json
            ${{ inputs.working-directory }}/target/index.html
            ${{ inputs.working-directory }}/target/manifest.json