parameters:
  - name: target
    type: string
  - name: working_directory
    type: string
  - name: profiles_directory
    type: string
  - name: snowflake_target_database
    type: string
  - name: snowflake_authenticator_value
    type: string
  - name: env_name
    type: string
    default: dbt-env    

steps:

  - bash: |
      source $DBT_ENV_NAME/bin/activate
      dbt snapshot --profiles-dir=${{ parameters.profiles_directory }} --target=${{ parameters.target }}
    displayName: Run Snapshots
    workingDirectory: ${{ parameters.working_directory }}
    env:
      DBT_ENV_NAME: ${{ parameters.env_name }}
      snowflake-target-database: ${{ parameters.snowflake_target_database }}
      snowflake-username: $(snowflake-username)
      snowflake-account: $(snowflake-account)
      snowflake-password: ${{ parameters.snowflake_authenticator_value }}
      snowflake-warehouse: $(snowflake-warehouse)
      snowflake-role: $(snowflake-role)
      snowflake-private-key-password: $(snowflake-private-key-password)
